### ISSUE TITLE
Instrument FadeOut Attribute Incorrectly Processed for IT Note Off Events

### ISSUE THREAD

**Issue by NoSuck** [cmatsuoka/libxmp#34] opened 2015-07-27 23:09 UTC
Hello.  I post for the first time but have been watching libxmp's progress for the past couple of years.  Of all the MOD playback libraries, libxmp has the most intelligent API design.  Thank you for making it.

I am currently looking at libxmp for use in a vim-like tracker and in a game engine but have run into some inconsistencies with how it renders IT files.  The biggest problem is libxmp's incorrect application of intstruments' FadeOut attributes upon note off (===) events.  I have prepared [a sample IT file](https://www.dropbox.com/l/YiCeQv6ozlSKEmdATN9BZj?text=1) with captured output from both libxmp's `examples/player-simple` program and Impulse Tracker 2.14 (run through DOSBox).  The following image files show captured output in stereo.  (Incidentally, they also illustrate an error in libxmp's stereo separation.  I will open a separate issue for this.)

![libxmp](https://nosuckdotorg.files.wordpress.com/2015/07/note-off-fadeout-256-screen-libxmp.png)
Libxmp

![Impulse Tracker](https://nosuckdotorg.files.wordpress.com/2015/07/note-off-fadeout-256-screen-impulse-tracker.png)
Impulse Tracker

Note:  The sample IT file's FadeOut value of 256 lies outside the valid range of 0-128, inclusive.  Changing this value to 128 produces more or less the same result.

**Comment by cmatsuoka** [comment] 2015-08-01 10:17
Thanks for reporting. Could you send the sample file to me directly? It
seems that Dropbox doesn't like me this morning and I'm not being able to
retrieve the file.

**Comment by NoSuck** [comment] 2015-08-01 22:24
Whoops.  I'm new to Dropbox and don't yet know how to share things.  Does the following link work?

https://www.dropbox.com/sh/vhs0u7lmh0wmjwh/AABOXrirOTsG0LrJL8Hj5LeIa?dl=0

**Comment by cmatsuoka** [comment] 2015-08-01 23:20
Thanks, it worked. I'll see what's happening and fix the player
accordingly.

**Comment by cmatsuoka** [comment] 2015-08-02 12:54
There was a problem in the way we handled envelope release + fadeout in IT files in envelopes with loops. I'm not 100% sure that this is the correct way to handle this, but it covers your case without breaking the OpenMPT tests. I'll add your sample file to the automated regression tests. The fix will be available in 4.3.10.

![image](https://cloud.githubusercontent.com/assets/317355/9026181/437d3bce-38fc-11e5-8db4-585757ec050f.png)

**Comment by cmatsuoka** [comment] 2016-02-29 18:40
It seems to be fixed, so I'll close this issue.

**Closed by cmatsuoka** 2016-02-29 18:40 UTC
