### ISSUE TITLE
A few mod playback bugs

### ISSUE THREAD

**Issue by leilei-** [cmatsuoka/libxmp#59] opened 2016-06-10 12:00 UTC
Current repository master.

Apologies in advance for packing many issues as one issue 

These are all related to .mod playback, though not of the traditional protrackery amiga made-for-Paula kind but rather 8ch+ reproductions of snes music transcribed for fun and learning with .mod's limitations   

1: Using Set Panning (E8x) on one channel seems to make the whole module mono, or at least not very stereo...unless i'm missing something.  

2: High notes seem to get bumped up one note for some reason, like F#8 becoming G-8. [example](http://leileilol.mancubus.net/mods/xmpl/issue2a.mod)

3: Setting a Note Delay (EDx), after a Set Volume (Cxx) with no sample set on the new delayed note will cause a note at the sample's default volume, ignoring the volume set by the command earlier.  This can break some echo tricks. [example](http://leileilol.mancubus.net/mods/xmpl/issue3.mod)

I tracked in MPT 1 16.0206, also these bugs don't seem to occur in foo_dumb or even Cubic Player 1.6.

**Comment by knight-ryu12** [comment] 2016-06-10 13:41
maybe I think, it's pending problem.
Module detection is doing that. I assume.
2016/06/10 21:00 "leilei-" <notifications@github.com>:

**Comment by mldoering** [comment] 2016-06-10 16:38
Don't know if it helps. I could also check a protracker softmixing
replayer together with uade and export it to mp3.

E8x/panning will be ignore, tho iirc.

mld/uade team.

---
Digital unterschrieben mit GNU Privacy Guard
Fingerabdruck: 330F 99EE 65A7 DF35 BF20  B5DC A0DC 8F02 5B1E CC24

**Comment by cmatsuoka** [comment] 2016-06-10 19:37
@leilei- Some of these problems may be caused by tracker-specific quirks or attempts to emulate bugs, e.g. libxmp only applies Protracker quirks in modules that are likely to be Protracker modules. xxCH mods will usually play in FastTracker mode. I'll check the examples to see what could be happening here. Do you have an example for problem 1 as well?

**Comment by leilei-** [comment] 2016-06-10 21:11
Both examples feature problem 1 to me.  It doesn't occur on mods that don't use the set paanning (the typical amiga stuff works fine), I get full stereo in those, so i do know i have libxmp outputting in stereo through testing

**Comment by cmatsuoka** [comment] 2016-06-13 00:23
The stereo problem is related to the Fast Tracker replayer being used for 8CHN mods. Fixing.

**Comment by cmatsuoka** [comment] 2016-06-13 16:32
Issues (hopefully) fixed and available in master. If not, please reopen!

**Comment by leilei-** [comment] 2016-06-14 00:48
I compiled it and I like what I hear :)

Though I did notice there might/could be a similar issue to issue 3 regarding panning on a delayed note.

**Comment by cmatsuoka** [comment] 2016-06-14 10:12
Reopened. Could you find or build a test case to check this new issue 4?

**Comment by leilei-** [comment] 2016-06-14 23:26
It might be just all panning that's affected.  It occurs on the examples I posted, but since those are old transcriptions with some extreme panning values, here's a sensible example.

**Comment by cmatsuoka** [comment] 2016-07-18 06:49
To be addressed in the 4.4.1 development cycle.

**Comment by cmatsuoka** [comment] 2016-10-02 14:47
I believe issue 4 is caused by effect E8x not being implemented in the replayer. In pattern 01 channel 8 there's a E88 effect, followed by notes using instrument 7. Xmp is playing these notes in the left channel, are they supposed to be all centered? (OpenMPT effect reference for Fast Tracker states that E8x should reset the panning if a new instrument value is found, but if this is not the case I can add a special handing for mod files using E8x). I can't test with Fast Tracker 1 because it doesn't run in Dosemu, and Fast Tracker II behaves in a different way.

**Comment by cmatsuoka** [comment] 2016-10-02 23:48
Commit 2beedcb implements E8x and changes the set pan effect in the XM replayer to keep the previous pan setting if the module is a multichannel MOD. This should fix issue 4.

**Closed by cmatsuoka** 2016-10-02 23:48 UTC
Labels: bug, mod
