### ISSUE TITLE
ProTracker Stops To Early (No Last Beats)

### ISSUE THREAD

**Issue by TEOL85** [cmatsuoka/libxmp#70] opened 2016-08-05 13:27 UTC
I found that there is a bug in libxmp where the tunes don't seem to play until the end. Is there a way of fixing that. 

The main suspect and most prominent source I could find of this bug happening is the Lotus title music so far.

http://www.exotica.org.uk/wiki/Lotus_Esprit_Turbo_Challenge

**Comment by cmatsuoka** [comment] 2016-08-07 10:57
I tested mod.title from Lotus Esprit Turbo Challenge and it seem to play correctly until pattern 7/row 63 (position 15), compared to Protracker 2.3. Is there a specific portion that's missing for you?

**Comment by TEOL85** [comment] 2016-08-23 10:23
The Duh at the end but I use a frontended version so it's maybe behind on versions I don't know.

**Comment by TEOL85** [comment] 2016-08-24 10:57
Anyway this is the end bit that doesn't play. It's the dow noise before it loops on the explosion noise. 

https://youtu.be/Tn-Khszi-V4?t=1m34s

**Comment by cmatsuoka** [comment] 2016-08-27 23:44
Can you hear it using Protracker or a different player?

**Comment by mldoering** [comment] 2016-08-28 04:38
Am Sat, 27 Aug 2016 16:44:34 -0700
schrieb Claudio Matsuoka <notifications@github.com>:

> Can you hear it using Protracker or a different player?
> 

hmmh, iirc from my memory the mod is intended to be looping instead
of ending. Could be worth a check how it sounds with xmp then.

---
Digital unterschrieben mit GNU Privacy Guard
Fingerabdruck: 330F 99EE 65A7 DF35 BF20  B5DC A0DC 8F02 5B1E CC24

**Comment by TEOL85** [comment] 2016-08-28 09:23
Yes cmatsuoka Deliplayer/UADE plays the end part.

**Comment by cmatsuoka** [comment] 2016-10-02 01:41
That's the expected behavior when looping is disabled (and looping is disabled by default because otherwise all modules would be looping forever), so the player is playing the module as it was written by the author. I'm closing this, but feel free to reopen if you think it's not a looping problem and the player has a bug.

**Closed by cmatsuoka** 2016-10-02 01:41 UTC
Labels: can't reproduce, mod
