### ISSUE TITLE
[Future request/bug] in S3M Module, it's somekind glichy between Schism and xmp

### ISSUE THREAD

**Issue by knight-ryu12** [cmatsuoka/libxmp#56] opened 2016-05-18 22:18 UTC
first, read title.
http://modarchive.org/index.php?request=view_by_moduleid&query=73364
this module is hear different between other tracker, especially final mario coin and 1-up.
(using newest xmp in android)

**Comment by knight-ryu12** [comment] 2016-05-18 22:19
actually, that module is using Scream tracker 3.20

**Comment by cmatsuoka** [comment] 2016-05-19 18:32
Indeed it's different, and the actual notes suggest that the author intended it to be played as Schism Tracker plays it (with high notes). However, the module is marked as made with Scream Tracker, and Scream Tracker plays that last notes with period limits. I'm not sure how I'll handle this yet, but in the meantime I asked Jake Kaufman if he remembers what tracker was used to write this module.

**Comment by knight-ryu12** [comment] 2016-05-20 04:51
Oh thanks..

**Comment by sagamusix** [comment] 2016-06-01 16:59
The module was last saved with ModPlug Tracker, not ST3. However, no MPT version I am aware of plays the notes "as intended". Detection-wise, you are most likely out of luck here.

**Comment by knight-ryu12** [comment] 2016-06-03 11:04
I think there is a no way to fixing this. I think real tracker(Which runs in DOS or DOSBOX Emu) can play it normal. AFAIK.
Well, I'll keep this thing opened. If you don't want to mess up, please close.

**Comment by sagamusix** [comment] 2016-06-03 11:06
> I think real tracker(Which runs in DOS or DOSBOX Emu) can play it normal.

No, ST3 has a fixed period limit which e.g. OpenMPT (and I think also xmp?) adhere to.

**Comment by knight-ryu12** [comment] 2016-06-03 11:11
So... What..
No tracker can play it normally? 
Gee... Wow.

**Comment by sagamusix** [comment] 2016-06-03 11:14
Well, Schism Tracker and Impulse Tracker obviously can, but the problem is that the file cannot be identified as being written by either of those two applications. Hence, xmp's behaviour is technically correct. It is also not simply possible to remove those frequency limitations since other S3M modules that really were written in ST3  or ModPlug may rely on those limits.

**Comment by knight-ryu12** [comment] 2016-06-04 00:32
yeah true. I know IT-style player plays normally.

**Comment by cmatsuoka** [comment] 2016-06-04 00:42
I'm experimenting with a set of flags to fine tune the player "personality" in cases where it's impossible to detect what the author originally intended to do. So, for example, one could tell the player to play a specific S3M file as a generic S3M player, with ST3-only quirks, using ST3+GUS quirks, or in IT sample mode. It also allows the user to force generic MOD, Noisetracker or Protracker mode, and to enable/disable FT2 bug emulation. This should cover the cases where autodetection fails (tracker identified itself as a different tracker, module was written in one tracker and loaded/saved in another, etc.)

**Comment by knight-ryu12** [comment] 2016-06-04 08:57
Adding new options to forcing to play as-intended?
Maybe.

**Comment by knight-ryu12** [comment] 2016-07-16 07:21
seems it is done by 4.4 release! closing

**Closed** 2016-07-16 07:22 UTC
