### ISSUE TITLE
[Android] in m-i.S3M, Drum retrigger plays Drum normally

### ISSUE THREAD

**Issue by knight-ryu12** [cmatsuoka/libxmp#72] opened 2016-08-17 02:13 UTC
Read title.
Drum retrigger seems play drum sample twice as same volume.
Sorry for a lot of Bug rep! 👍

**Comment by cmatsuoka** [comment] 2016-08-18 13:57
Do you have a module where this problem happens, or an example to help me reproduce the problem?

**Comment by knight-ryu12** [comment] 2016-08-18 14:47
https://modarchive.org/index.php?request=view_by_moduleid&query=48473

2016/08/18 22:57 "Claudio Matsuoka" <notifications@github.com>:

**Comment by cmatsuoka** [comment] 2016-08-18 18:01
Sorry, I missed the module file name in the title.

This problem is really weird, it's playing a note that's not there. It will require some tracing to see where the player thinks this note comes from.

**Comment by knight-ryu12** [comment] 2016-08-18 18:11
FYI, this tune has trick. in Scream Tracker 3, it plays instrument with no
sample in it.
So this tune uses that and show something in info screen.

2016/08/19 3:01 "Claudio Matsuoka" <notifications@github.com>:

**Comment by knight-ryu12** [comment] 2016-08-18 18:13
Also All android bug rep is from Android 4.4.2. Xperia Z2 Tablet

**Comment by sagamusix** [comment] 2016-08-19 12:36
It looks like the problem is related to the sample loop points being set up, but the loop itself not being activated. I have created a minimal testcase to verify that:
[xxm-i.zip](https://github.com/cmatsuoka/libxmp/files/426958/xxm-i.zip)

knight-ryu12: Mod playback bugs are hardly ever platform-dependent, so I don't think you need to tag each of your issues with [Android], *especially* if Claudio can reproduce the issue on any other platform as well.

**Comment by cmatsuoka** [comment] 2016-08-21 14:58
In this module we hit a corner case where the sample was ending exactly at a frame boundary, and the sample was being looped even with the loop flag disabled. Fixed in 59380a2. All this logic will be refactored someday.

**Closed** 2016-08-21 15:09 UTC
Labels: bug, s3m
