### ISSUE TITLE
IT 8.88 is used for OpenMPT 1.17 files

### ISSUE THREAD

**Issue by vitalkanev** [cmatsuoka/libxmp#138] opened 2019-03-04 14:13 UTC
_[Android app](https://play.google.com/store/apps/details?id=org.helllabs.android.xmp) uses this library_

## Steps to reproduce

1. Play ftp://modland.com/pub/modules/Impulsetracker/TJ%20Technoiz/coop-Lyzzard/shorecrest%20pilgrimage.it

## Expected behaviour

IT 2.14 in version field

## Actual behaviour

IT 8.88 in version field

**Comment by sagamusix** [comment] 2019-04-11 07:20
Early OpenMPT versions wrote version 8.88 in the format version field, so claiming IT 2.14 format would be plain wrong.

**Comment by AliceLR** [comment] 2020-11-06 22:09
What exactly is the problem here? I can confirm that early versions of OpenMPT did save IT files with the version "8.88" (as it was one of the reasons I stuck with MPT 1.16 longer than I should have). Are you saying libxmp should misreport the version of the affected IT files (I disagree) or are you saying that IT 8.88 itself was a mistake (I think everyone agrees there)?

**Comment by sagamusix** [comment] 2020-11-06 22:10
Given the expected and actual behaviour descriptions, there is nothing to fix here. libxmp truthfully reports what is found in the file.

**Comment by sezero** [comment] 2020-11-06 22:11
I think we can close this as WONT-FIX.

**Closed** 2020-11-06 22:13 UTC
Labels: wontfix
